import type { AtlasRegistry } from './types';

export const atlasRegistry: AtlasRegistry = {
  frames: [
    {
      id: 'admin-dashboard',
      name: 'Admin Dashboard',
      route: '/admin',
      domain: 'admin',
      roles: ['system_admin'],
      components: ['admin-shell-v2', 'admin-overview-stats', 'admin-activity-feed'],
      reads: ['tenants', 'users'],
      writes: [],
      endpoints: [],
      tags: ['system', 'overview'],
      owner: 'platform',
      fileRef: 'app/admin/page.tsx',
    },
    {
      id: 'admin-users',
      name: 'User Management',
      route: '/admin/users',
      domain: 'admin',
      roles: ['system_admin'],
      components: ['admin-shell-v2', 'user-list-table', 'user-table-toolbar'],
      reads: ['users', 'tenant_memberships'],
      writes: ['tenant_memberships'],
      endpoints: [],
      tags: ['rbac'],
      owner: 'platform',
      fileRef: 'app/admin/users/page.tsx',
    },
    {
      id: 'tenant-dashboard',
      name: 'Tenant Dashboard',
      route: '/admin/tenant/[tenantId]',
      domain: 'admin',
      roles: ['system_admin', 'tenant_admin'],
      components: ['admin-shell-v2', 'admin-page-header'],
      reads: ['tenants', 'tenant_memberships'],
      writes: [],
      endpoints: [],
      tags: ['tenant'],
      owner: 'admin-team',
      fileRef: 'app/admin/tenant/[tenantId]/page.tsx',
    },
    {
      id: 'tenant-achievements',
      name: 'Tenant Achievements',
      route: '/admin/tenant/[tenantId]/gamification/achievements',
      domain: 'admin',
      roles: ['system_admin', 'tenant_admin'],
      components: ['admin-shell-v2', 'admin-data-table', 'admin-bulk-actions'],
      reads: ['achievements', 'achievement_awards'],
      writes: ['achievements', 'achievement_awards'],
      endpoints: ['gamification-pins'],
      tags: ['gamification', 'tenant'],
      owner: 'gamification',
      fileRef: 'app/admin/tenant/[tenantId]/gamification/achievements/page.tsx',
    },
    {
      id: 'admin-achievements',
      name: 'Achievements Admin',
      route: '/admin/achievements',
      domain: 'admin',
      roles: ['system_admin'],
      components: ['admin-shell-v2', 'achievement-library-grid'],
      reads: ['achievements'],
      writes: ['achievement_awards'],
      endpoints: ['admin-award-presets'],
      tags: ['gamification'],
      owner: 'gamification',
      fileRef: 'app/admin/achievements/page.tsx',
    },
    {
      id: 'app-home',
      name: 'App Home',
      route: '/app',
      domain: 'product',
      roles: ['leader', 'participant'],
      components: ['app-shell', 'app-dashboard-page'],
      reads: ['game_sessions'],
      writes: [],
      endpoints: ['gamification-events'],
      tags: ['home'],
      owner: 'product',
      fileRef: 'app/app/page.tsx',
    },
    {
      id: 'app-browse',
      name: 'Browse Games',
      route: '/app/browse',
      domain: 'games',
      roles: ['leader', 'participant'],
      components: ['app-shell', 'browse-search', 'browse-filter-bar', 'browse-game-card'],
      reads: ['games'],
      writes: [],
      endpoints: ['games-list'],
      tags: ['browse'],
      owner: 'content',
      fileRef: 'app/app/browse/page.tsx',
    },
    {
      id: 'app-play-start',
      name: 'Start Game Session',
      route: '/app/play/[gameId]',
      domain: 'games',
      roles: ['leader', 'participant'],
      components: ['app-shell', 'start-session-button'],
      reads: ['games'],
      writes: ['game_sessions'],
      endpoints: ['games-list'],
      tags: ['play'],
      owner: 'content',
      fileRef: 'app/app/play/[gameId]/page.tsx',
    },
    {
      id: 'app-planner',
      name: 'Planner',
      route: '/app/planner',
      domain: 'planner',
      roles: ['leader', 'participant'],
      components: ['app-shell', 'planner-page', 'planner-header'],
      reads: ['plans', 'plan_blocks', 'plan_play_progress'],
      writes: ['plan_blocks'],
      endpoints: [],
      tags: ['planning'],
      owner: 'planner-team',
      fileRef: 'app/app/planner/page.tsx',
    },
    {
      id: 'app-profile',
      name: 'Profile',
      route: '/app/profile',
      domain: 'product',
      roles: ['leader', 'participant'],
      components: ['app-shell', 'profile-page'],
      reads: ['user_achievements'],
      writes: [],
      endpoints: ['gamification-pins'],
      tags: ['profile'],
      owner: 'product',
      fileRef: 'app/app/profile/page.tsx',
    },
  ],
  components: [
    { id: 'admin-shell-v2', name: 'AdminShellV2', fileRef: 'components/admin/AdminShellV2.tsx' },
    { id: 'admin-overview-stats', name: 'OverviewStats', fileRef: 'features/admin/dashboard/components/OverviewStats.tsx' },
    { id: 'admin-activity-feed', name: 'ActivityFeed', fileRef: 'features/admin/dashboard/components/ActivityFeed.tsx' },
    { id: 'user-list-table', name: 'UserListTable', fileRef: 'features/admin/users/components/list/UserListTable.tsx' },
    { id: 'user-table-toolbar', name: 'UserTableToolbar', fileRef: 'features/admin/users/components/UserTableToolbar.tsx' },
    { id: 'admin-page-header', name: 'AdminPageHeader', fileRef: 'components/admin/shared/AdminPageHeader.tsx' },
    { id: 'admin-data-table', name: 'AdminDataTable', fileRef: 'components/admin/shared/AdminDataTable.tsx' },
    { id: 'admin-bulk-actions', name: 'AdminBulkActions', fileRef: 'components/admin/shared/AdminBulkActions.tsx' },
    { id: 'achievement-library-grid', name: 'AchievementLibraryGrid', fileRef: 'features/admin/achievements/components/AchievementLibraryGrid.tsx' },
    { id: 'app-shell', name: 'AppShell', fileRef: 'components/app/AppShell.tsx' },
    { id: 'app-dashboard-page', name: 'AppDashboardPage', fileRef: 'features/journey/AppDashboardPage.tsx' },
    { id: 'browse-search', name: 'SearchBar', fileRef: 'features/browse/components/SearchBar.tsx' },
    { id: 'browse-filter-bar', name: 'FilterBar', fileRef: 'features/browse/components/FilterBar.tsx' },
    { id: 'browse-game-card', name: 'GameCard', fileRef: 'features/browse/components/GameCard.tsx' },
    { id: 'start-session-button', name: 'StartSessionButton', fileRef: 'app/app/play/[gameId]/start-session-button.tsx' },
    { id: 'planner-page', name: 'PlannerPage', fileRef: 'features/planner/PlannerPage.tsx' },
    { id: 'planner-header', name: 'PlanHeaderBar', fileRef: 'features/planner/components/PlanHeaderBar.tsx' },
    { id: 'profile-page', name: 'ProfilePage', fileRef: 'features/profile/ProfilePage.tsx' },
  ],
  tables: [
    { id: 'tenants', name: 'tenants', schema: 'public', description: 'Tenant organizations' },
    { id: 'tenant_memberships', name: 'tenant_memberships', schema: 'public', description: 'Tenant roles' },
    { id: 'users', name: 'users', schema: 'auth', description: 'User accounts' },
    { id: 'games', name: 'games', schema: 'public', description: 'Game catalog' },
    { id: 'game_sessions', name: 'game_sessions', schema: 'public', description: 'Play sessions' },
    { id: 'plans', name: 'plans', schema: 'public', description: 'Planner plans' },
    { id: 'plan_blocks', name: 'plan_blocks', schema: 'public', description: 'Planner blocks' },
    { id: 'plan_play_progress', name: 'plan_play_progress', schema: 'public', description: 'Planner play progress' },
    { id: 'achievements', name: 'achievements', schema: 'public', description: 'Achievement definitions' },
    { id: 'achievement_awards', name: 'achievement_awards', schema: 'public', description: 'Award records' },
    { id: 'user_achievements', name: 'user_achievements', schema: 'public', description: 'User achievement states' },
  ],
  endpoints: [
    {
      id: 'games-list',
      method: 'GET',
      path: '/api/games',
      description: 'List games',
      fileRef: 'app/api/games/route.ts',
    },
    {
      id: 'games-create',
      method: 'POST',
      path: '/api/games',
      description: 'Create game',
      fileRef: 'app/api/games/route.ts',
    },
    {
      id: 'games-import',
      method: 'POST',
      path: '/api/games/csv-import',
      description: 'Import games CSV',
      fileRef: 'app/api/games/csv-import/route.ts',
    },
    {
      id: 'games-export',
      method: 'GET',
      path: '/api/games/csv-export',
      description: 'Export games CSV',
      fileRef: 'app/api/games/csv-export/route.ts',
    },
    {
      id: 'admin-award-presets',
      method: 'POST',
      path: '/api/admin/award-builder/presets',
      description: 'Award builder presets',
      fileRef: 'app/api/admin/award-builder/presets/route.ts',
    },
    {
      id: 'gamification-pins',
      method: 'GET',
      path: '/api/gamification/pins',
      description: 'Pinned achievements',
      fileRef: 'app/api/gamification/pins/route.ts',
    },
    {
      id: 'gamification-events',
      method: 'GET',
      path: '/api/gamification/events',
      description: 'Gamification events',
      fileRef: 'app/api/gamification/events/route.ts',
    },
    {
      id: 'gamification-leaderboard',
      method: 'GET',
      path: '/api/gamification/leaderboard',
      description: 'Leaderboard data',
      fileRef: 'app/api/gamification/leaderboard/route.ts',
    },
  ],
  edges: [
    { fromType: 'frame', fromId: 'admin-dashboard', toType: 'component', toId: 'admin-shell-v2', relation: 'uses' },
    { fromType: 'frame', fromId: 'admin-dashboard', toType: 'component', toId: 'admin-overview-stats', relation: 'uses' },
    { fromType: 'frame', fromId: 'admin-dashboard', toType: 'component', toId: 'admin-activity-feed', relation: 'uses' },
    { fromType: 'frame', fromId: 'admin-dashboard', toType: 'table', toId: 'tenants', relation: 'reads' },
    { fromType: 'frame', fromId: 'admin-dashboard', toType: 'table', toId: 'users', relation: 'reads' },

    { fromType: 'frame', fromId: 'admin-users', toType: 'component', toId: 'user-list-table', relation: 'uses' },
    { fromType: 'frame', fromId: 'admin-users', toType: 'component', toId: 'user-table-toolbar', relation: 'uses' },
    { fromType: 'frame', fromId: 'admin-users', toType: 'table', toId: 'users', relation: 'reads' },
    { fromType: 'frame', fromId: 'admin-users', toType: 'table', toId: 'tenant_memberships', relation: 'writes' },

    { fromType: 'frame', fromId: 'tenant-dashboard', toType: 'component', toId: 'admin-page-header', relation: 'uses' },
    { fromType: 'frame', fromId: 'tenant-dashboard', toType: 'table', toId: 'tenants', relation: 'reads' },
    { fromType: 'frame', fromId: 'tenant-dashboard', toType: 'table', toId: 'tenant_memberships', relation: 'reads' },

    { fromType: 'frame', fromId: 'tenant-achievements', toType: 'component', toId: 'admin-data-table', relation: 'uses' },
    { fromType: 'frame', fromId: 'tenant-achievements', toType: 'component', toId: 'admin-bulk-actions', relation: 'uses' },
    { fromType: 'frame', fromId: 'tenant-achievements', toType: 'table', toId: 'achievements', relation: 'reads' },
    { fromType: 'frame', fromId: 'tenant-achievements', toType: 'table', toId: 'achievement_awards', relation: 'writes' },
    { fromType: 'frame', fromId: 'tenant-achievements', toType: 'endpoint', toId: 'gamification-pins', relation: 'calls' },

    { fromType: 'frame', fromId: 'admin-achievements', toType: 'component', toId: 'achievement-library-grid', relation: 'uses' },
    { fromType: 'frame', fromId: 'admin-achievements', toType: 'table', toId: 'achievements', relation: 'reads' },
    { fromType: 'frame', fromId: 'admin-achievements', toType: 'table', toId: 'achievement_awards', relation: 'writes' },
    { fromType: 'frame', fromId: 'admin-achievements', toType: 'endpoint', toId: 'admin-award-presets', relation: 'calls' },

    { fromType: 'frame', fromId: 'app-home', toType: 'component', toId: 'app-shell', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-home', toType: 'component', toId: 'app-dashboard-page', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-home', toType: 'table', toId: 'game_sessions', relation: 'reads' },
    { fromType: 'frame', fromId: 'app-home', toType: 'endpoint', toId: 'gamification-events', relation: 'calls' },

    { fromType: 'frame', fromId: 'app-browse', toType: 'component', toId: 'browse-search', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-browse', toType: 'component', toId: 'browse-filter-bar', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-browse', toType: 'component', toId: 'browse-game-card', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-browse', toType: 'table', toId: 'games', relation: 'reads' },
    { fromType: 'frame', fromId: 'app-browse', toType: 'endpoint', toId: 'games-list', relation: 'calls' },

    { fromType: 'frame', fromId: 'app-play-start', toType: 'component', toId: 'start-session-button', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-play-start', toType: 'table', toId: 'games', relation: 'reads' },
    { fromType: 'frame', fromId: 'app-play-start', toType: 'table', toId: 'game_sessions', relation: 'writes' },

    { fromType: 'frame', fromId: 'app-planner', toType: 'component', toId: 'planner-page', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-planner', toType: 'component', toId: 'planner-header', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-planner', toType: 'table', toId: 'plans', relation: 'reads' },
    { fromType: 'frame', fromId: 'app-planner', toType: 'table', toId: 'plan_blocks', relation: 'writes' },

    { fromType: 'frame', fromId: 'app-profile', toType: 'component', toId: 'profile-page', relation: 'uses' },
    { fromType: 'frame', fromId: 'app-profile', toType: 'table', toId: 'user_achievements', relation: 'reads' },
    { fromType: 'frame', fromId: 'app-profile', toType: 'endpoint', toId: 'gamification-pins', relation: 'calls' },
  ],
};

// TODO: Auto-discover routes, endpoints, and schema for system sync.
