-- ============================================================================
-- system_jobs_runs — per-invocation monitoring rows for scheduled jobs
-- ============================================================================
-- One row per edge-function invocation. Enables:
--   • Admin "Jobs health" dashboard (SQL view or UI)
--   • Alert rules on remaining / errors / timeout
--   • Incident correlation via run_id
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.system_jobs_runs (
  id            uuid PRIMARY KEY,              -- = runId generated by the job
  job_name      text NOT NULL,                 -- e.g. 'purge_anonymized_tenants'
  status        text NOT NULL DEFAULT 'running' CHECK (status IN ('running','ok','warn','fail')),
  started_at    timestamptz NOT NULL DEFAULT now(),
  finished_at   timestamptz,
  purged        int NOT NULL DEFAULT 0,
  remaining     int NOT NULL DEFAULT 0,
  skipped_timeout int NOT NULL DEFAULT 0,
  elapsed_ms    int,
  errors        jsonb DEFAULT '[]'::jsonb,
  metadata      jsonb DEFAULT '{}'::jsonb       -- dry_run flag, batch_limit, etc.
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_system_jobs_runs_job_name_started
  ON public.system_jobs_runs (job_name, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_system_jobs_runs_status
  ON public.system_jobs_runs (status) WHERE status != 'ok';

-- RLS: system_admin read-only, service_role writes bypass RLS
ALTER TABLE public.system_jobs_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "system_jobs_runs_select" ON public.system_jobs_runs;
CREATE POLICY "system_jobs_runs_select" ON public.system_jobs_runs
  FOR SELECT
  USING (public.is_system_admin());

COMMENT ON TABLE public.system_jobs_runs IS
  'Per-invocation run log for scheduled jobs. One row per execution.';
COMMENT ON COLUMN public.system_jobs_runs.id IS
  'Same as the runId generated by the edge function — used for log correlation.';
COMMENT ON COLUMN public.system_jobs_runs.errors IS
  'Array of error strings from the run. MUST NOT contain PII.';
