import type { AchievementItem, AchievementTheme } from "./types";

export const themes: AchievementTheme[] = [
  {
    id: "gold_default",
    name: "Guld",
    colors: {
      base: { color: "#F1C232" },
      background: { color: "#F59E0B" },
      foreground: { color: "#FBBF24" },
      symbol: { color: "#FFF7ED" },
    },
  },
  {
    id: "silver_default",
    name: "Silver",
    colors: {
      base: { color: "#D1D5DB" },
      background: { color: "#9CA3AF" },
      foreground: { color: "#E5E7EB" },
      symbol: { color: "#F9FAFB" },
    },
  },
  {
    id: "emerald",
    name: "Emerald",
    colors: {
      base: { color: "#10B981" },
      background: { color: "#059669" },
      foreground: { color: "#34D399" },
      symbol: { color: "#ECFDF3" },
    },
  },
  {
    id: "amethyst",
    name: "Amethyst",
    colors: {
      base: { color: "#8B5CF6" },
      background: { color: "#7C3AED" },
      foreground: { color: "#A78BFA" },
      symbol: { color: "#F5F3FF" },
    },
  },
  {
    id: "ruby",
    name: "Ruby",
    colors: {
      base: { color: "#EF4444" },
      background: { color: "#B91C1C" },
      foreground: { color: "#F87171" },
      symbol: { color: "#FEF2F2" },
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    colors: {
      base: { color: "#0EA5E9" },
      background: { color: "#0369A1" },
      foreground: { color: "#38BDF8" },
      symbol: { color: "#E0F2FE" },
    },
  },
];

export const mockAchievements: AchievementItem[] = [
  {
    id: "achv-1",
    title: "Core Pathfinder",
    subtitle: "Complete onboarding",
    description: "Finish the onboarding flow and unlock the core badge.",
    rewardCoins: 50,
    profileFrameSync: { enabled: true, durationDays: 7, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 3,
    availableForOrgs: ["org-1", "org-2"],
    icon: {
      mode: "theme",
      themeId: "amethyst",
      size: "lg",
      base: { id: "base_shield" },
      backgrounds: [{ id: "bg_wings_2" }],
      foregrounds: [{ id: "fg_stars_3" }],
      symbol: { id: "ic_flash" },
      layers: {
        base: "base_shield",
        background: "bg_wings_2",
        foreground: "fg_stars_3",
        symbol: "ic_flash",
      },
    },
  },
  {
    id: "achv-2",
    title: "Gamification Pro",
    subtitle: "Launch your first quest",
    description: "Publish a gamified quest with rewards.",
    rewardCoins: 120,
    profileFrameSync: { enabled: false },
    publishedRoles: ["admin"],
    status: "draft",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "custom",
      themeId: "emerald",
      size: "lg",
      base: { id: "base_circle" },
      backgrounds: [{ id: "bg_spikes_3" }],
      foregrounds: [{ id: "fg_queen_crown_1" }],
      symbol: { id: "ic_medalj" },
      layers: {
        base: "base_circle",
        background: "bg_spikes_3",
        foreground: "fg_queen_crown_1",
        symbol: "ic_medalj",
      },
      customColors: {
        base: "#0EA5E9",
        background: "#10B981",
        foreground: "#FBBF24",
        symbol: "#F8FAFC",
      },
    },
  },

  // ============================================================================
  // SHIELD SERIES - Ruby/Red theme, Wings 1-4
  // ============================================================================
  {
    id: "shield-ruby-lvl1",
    title: "Sköld Brons",
    subtitle: "Nivå 1",
    description: "Första steget på Shield-resan. Wings 1 visar att du börjat.",
    rewardCoins: 25,
    profileFrameSync: { enabled: true, durationDays: 3, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "ruby",
      size: "lg",
      base: { id: "base_shield" },
      backgrounds: [{ id: "bg_wings_1" }],
      foregrounds: [],
      symbol: { id: "ic_singlestar" },
    },
  },
  {
    id: "shield-ruby-lvl2",
    title: "Sköld Silver",
    subtitle: "Nivå 2",
    description: "Du har gjort framsteg! Wings 2 visar din utveckling.",
    rewardCoins: 50,
    profileFrameSync: { enabled: true, durationDays: 5, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "ruby",
      size: "lg",
      base: { id: "base_shield" },
      backgrounds: [{ id: "bg_wings_2" }],
      foregrounds: [{ id: "fg_stars_1" }],
      symbol: { id: "ic_dobblestar" },
    },
  },
  {
    id: "shield-ruby-lvl3",
    title: "Sköld Guld",
    subtitle: "Nivå 3",
    description: "Imponerande! Wings 3 visar mästerskap.",
    rewardCoins: 100,
    profileFrameSync: { enabled: true, durationDays: 7, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "ruby",
      size: "lg",
      base: { id: "base_shield" },
      backgrounds: [{ id: "bg_wings_3" }],
      foregrounds: [{ id: "fg_stars_2" }],
      symbol: { id: "ic_crown" },
    },
  },
  {
    id: "shield-ruby-lvl4",
    title: "Sköld Legend",
    subtitle: "Nivå 4 - Max",
    description: "Legendstatus! Wings 4 är den ultimata nivån.",
    rewardCoins: 200,
    profileFrameSync: { enabled: true, durationDays: 14, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "ruby",
      size: "lg",
      base: { id: "base_shield" },
      backgrounds: [{ id: "bg_wings_4" }],
      foregrounds: [{ id: "fg_king_crown_1" }],
      symbol: { id: "ic_pokal" },
    },
  },

  // ============================================================================
  // CIRCLE SERIES - Emerald/Green theme, Wings 1-4
  // ============================================================================
  {
    id: "circle-emerald-lvl1",
    title: "Cirkel Brons",
    subtitle: "Nivå 1",
    description: "Välkommen till Circle-serien. Wings 1.",
    rewardCoins: 25,
    profileFrameSync: { enabled: true, durationDays: 3, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "emerald",
      size: "lg",
      base: { id: "base_circle" },
      backgrounds: [{ id: "bg_wings_1" }],
      foregrounds: [],
      symbol: { id: "ic_heart" },
    },
  },
  {
    id: "circle-emerald-lvl2",
    title: "Cirkel Silver",
    subtitle: "Nivå 2",
    description: "Fortsätt så! Wings 2 visar dedikation.",
    rewardCoins: 50,
    profileFrameSync: { enabled: true, durationDays: 5, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "emerald",
      size: "lg",
      base: { id: "base_circle" },
      backgrounds: [{ id: "bg_wings_2" }],
      foregrounds: [{ id: "fg_ribbon_1" }],
      symbol: { id: "ic_lvlup" },
    },
  },
  {
    id: "circle-emerald-lvl3",
    title: "Cirkel Guld",
    subtitle: "Nivå 3",
    description: "Fantastiskt arbete! Wings 3.",
    rewardCoins: 100,
    profileFrameSync: { enabled: true, durationDays: 7, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "emerald",
      size: "lg",
      base: { id: "base_circle" },
      backgrounds: [{ id: "bg_wings_3" }],
      foregrounds: [{ id: "fg_stars_3" }],
      symbol: { id: "ic_team" },
    },
  },
  {
    id: "circle-emerald-lvl4",
    title: "Cirkel Legend",
    subtitle: "Nivå 4 - Max",
    description: "Du har nått toppen! Wings 4 och Legend-status.",
    rewardCoins: 200,
    profileFrameSync: { enabled: true, durationDays: 14, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "emerald",
      size: "lg",
      base: { id: "base_circle" },
      backgrounds: [{ id: "bg_wings_4" }],
      foregrounds: [{ id: "fg_queen_crown_1" }],
      symbol: { id: "ic_chest" },
    },
  },

  // ============================================================================
  // HEXAGON SERIES - Arctic/Blue theme, Wings 1-4
  // ============================================================================
  {
    id: "hexagon-arctic-lvl1",
    title: "Hexagon Brons",
    subtitle: "Nivå 1",
    description: "Starten på Hexagon-serien. Wings 1.",
    rewardCoins: 25,
    profileFrameSync: { enabled: true, durationDays: 3, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "arctic",
      size: "lg",
      base: { id: "base_hexagon" },
      backgrounds: [{ id: "bg_wings_1" }],
      foregrounds: [],
      symbol: { id: "ic_signal" },
    },
  },
  {
    id: "hexagon-arctic-lvl2",
    title: "Hexagon Silver",
    subtitle: "Nivå 2",
    description: "Du växer! Wings 2.",
    rewardCoins: 50,
    profileFrameSync: { enabled: true, durationDays: 5, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "arctic",
      size: "lg",
      base: { id: "base_hexagon" },
      backgrounds: [{ id: "bg_wings_2" }],
      foregrounds: [{ id: "fg_stars_1-1" }],
      symbol: { id: "ic_communicate" },
    },
  },
  {
    id: "hexagon-arctic-lvl3",
    title: "Hexagon Guld",
    subtitle: "Nivå 3",
    description: "Expert-nivå! Wings 3.",
    rewardCoins: 100,
    profileFrameSync: { enabled: true, durationDays: 7, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "arctic",
      size: "lg",
      base: { id: "base_hexagon" },
      backgrounds: [{ id: "bg_wings_3" }],
      foregrounds: [{ id: "fg_stars_4" }],
      symbol: { id: "ic_flash" },
    },
  },
  {
    id: "hexagon-arctic-lvl4",
    title: "Hexagon Legend",
    subtitle: "Nivå 4 - Max",
    description: "Legendarisk! Wings 4 med alla dekoration.",
    rewardCoins: 200,
    profileFrameSync: { enabled: true, durationDays: 14, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "arctic",
      size: "lg",
      base: { id: "base_hexagon" },
      backgrounds: [{ id: "bg_wings_4" }],
      foregrounds: [{ id: "fg_king_crown_2" }],
      symbol: { id: "ic_tourch" },
    },
  },

  // ============================================================================
  // DIAMOND SERIES - Amethyst/Purple theme, Wings 1-4
  // ============================================================================
  {
    id: "diamond-amethyst-lvl1",
    title: "Diamant Brons",
    subtitle: "Nivå 1",
    description: "Diamond-serien börjar här. Wings 1.",
    rewardCoins: 25,
    profileFrameSync: { enabled: true, durationDays: 3, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "amethyst",
      size: "lg",
      base: { id: "base_diamond" },
      backgrounds: [{ id: "bg_wings_1" }],
      foregrounds: [],
      symbol: { id: "ic_ember" },
    },
  },
  {
    id: "diamond-amethyst-lvl2",
    title: "Diamant Silver",
    subtitle: "Nivå 2",
    description: "Uppgradering! Wings 2.",
    rewardCoins: 50,
    profileFrameSync: { enabled: true, durationDays: 5, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "amethyst",
      size: "lg",
      base: { id: "base_diamond" },
      backgrounds: [{ id: "bg_wings_2" }],
      foregrounds: [{ id: "fg_ribbon_2" }],
      symbol: { id: "ic_arrow_up" },
    },
  },
  {
    id: "diamond-amethyst-lvl3",
    title: "Diamant Guld",
    subtitle: "Nivå 3",
    description: "Guldnivå! Wings 3 med extra glans.",
    rewardCoins: 100,
    profileFrameSync: { enabled: true, durationDays: 7, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "amethyst",
      size: "lg",
      base: { id: "base_diamond" },
      backgrounds: [{ id: "bg_wings_3" }],
      foregrounds: [{ id: "fg_stars_2" }],
      symbol: { id: "ic_medalj" },
    },
  },
  {
    id: "diamond-amethyst-lvl4",
    title: "Diamant Legend",
    subtitle: "Nivå 4 - Max",
    description: "Maximum! Wings 4 och full Legend-status.",
    rewardCoins: 200,
    profileFrameSync: { enabled: true, durationDays: 14, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "amethyst",
      size: "lg",
      base: { id: "base_diamond" },
      backgrounds: [{ id: "bg_wings_4" }],
      foregrounds: [{ id: "fg_queen_crown_2" }],
      symbol: { id: "ic_crown" },
    },
  },

  // ============================================================================
  // GOLD SERIES - Gold theme, mixed bases, Wings 1-4
  // ============================================================================
  {
    id: "gold-series-lvl1",
    title: "Guld Nybörjare",
    subtitle: "Nivå 1",
    description: "Guld-serien med Pentagon base. Wings 1.",
    rewardCoins: 30,
    profileFrameSync: { enabled: true, durationDays: 3, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "gold_default",
      size: "lg",
      base: { id: "base_pentagon" },
      backgrounds: [{ id: "bg_wings_1" }],
      foregrounds: [],
      symbol: { id: "ic_book" },
    },
  },
  {
    id: "gold-series-lvl2",
    title: "Guld Medel",
    subtitle: "Nivå 2",
    description: "Fortsätt med Guld! Laurel Ring base. Wings 2.",
    rewardCoins: 60,
    profileFrameSync: { enabled: true, durationDays: 5, useBase: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "gold_default",
      size: "lg",
      base: { id: "base_laurel_ring1" },
      backgrounds: [{ id: "bg_wings_2" }],
      foregrounds: [{ id: "fg_stars_1" }],
      symbol: { id: "ic_checkmark" },
    },
  },
  {
    id: "gold-series-lvl3",
    title: "Guld Avancerad",
    subtitle: "Nivå 3",
    description: "Nästan där! Laurel Ring 2 base. Wings 3.",
    rewardCoins: 120,
    profileFrameSync: { enabled: true, durationDays: 7, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "gold_default",
      size: "lg",
      base: { id: "base_laurel_ring2" },
      backgrounds: [{ id: "bg_wings_3" }],
      foregrounds: [{ id: "fg_stars_3" }],
      symbol: { id: "ic_deal" },
    },
  },
  {
    id: "gold-series-lvl4",
    title: "Guld Mästare",
    subtitle: "Nivå 4 - Max",
    description: "Den ultimata guldutmärkelsen! Shield base. Wings 4.",
    rewardCoins: 250,
    profileFrameSync: { enabled: true, durationDays: 14, useBase: true, useForeground: true },
    publishedRoles: ["admin", "creator"],
    status: "published",
    version: 1,
    availableForOrgs: [],
    icon: {
      mode: "theme",
      themeId: "gold_default",
      size: "lg",
      base: { id: "base_shield" },
      backgrounds: [{ id: "bg_wings_4" }],
      foregrounds: [{ id: "fg_king_crown_1" }],
      symbol: { id: "ic_pokal" },
    },
  },
];
